from .collection_extensions import CollectionExtensions
from .color_helper import ColorHelper
from .string_utils import StringUtils

from .math_utils import lerp, gaussian_exponential_kernel_confidence_factor, gaussian_exponential_kernel_confidence_percentage
from .data_analysis import SimilarityScorer
